version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: sentiment-sense-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example  # Parola root pentru MySQL
      MYSQL_DATABASE: sentimentsense_db  # Numele bazei de date
      MYSQL_USER: user  # Utilizator definit pentru acces
      MYSQL_PASSWORD: password  # Parola utilizatorului definit
    ports:
      - "3306:3306"  # Portul MySQL
    networks:
      - sentiment-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    networks:
      - sentiment-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - sentiment-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - sentiment-network

  sentiment-sense-app:
    build: .
    container_name: sentiment-sense-app
    depends_on:
      - mysql
      - kafka
    ports:
      - "8080:8080"  # Aplicația Spring va rula pe acest port
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - sentiment-network

networks:
  sentiment-network:
    driver: bridge
