spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sentimentsense_db  # MySQL database address from the container
    username: user  # User name defined in docker-compose.yml
    password: password  # Password defined docker-compose.yml
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  sql:
    init:
      mode: always # Runs SQL init scripts on startup. Adjust this based on your environment needs.
  jpa:
    hibernate:
      ddl-auto: update # Automatically updates the schema. Set this to 'none' in production for safety.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL dialect for JPA
    show-sql: true # Enable to see SQL queries in the log. Can be set to false for production.

  kafka:
    bootstrap-servers: kafka:9092  # Kafka runs in a separate container
    consumer:
        group-id: sentiment-group
        auto-offset-reset: earliest
        enable-auto-commit: true
    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
        missing-topics-fatal: false  # If any topic is missing the application won't stop

server:
  port: 8080  # The port on which the application is running

logging:
  level:
    org:
      springframework:
        kafka: debug  # To get detailed logs related to Kafka
